name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:

  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build:production
        
      - name: Verify build artifacts
        run: |
          if [ ! -d "build" ]; then
            echo "❌ Build directory not found"
            exit 1
          fi
          if [ ! -f "build/index.html" ]; then
            echo "❌ Main HTML file not found"
            exit 1
          fi
          echo "✅ Build artifacts verified"

  notification:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: build-validation
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Notify deployment status
        run: |
          echo "🚀 Build validation completed successfully"
          echo "📦 Vercel will automatically deploy from this commit"
          echo "🔗 Monitor deployment status at: https://vercel.com/dashboard"